seed: 42

model:
  name: "facebook/wav2vec2-base-960h"   # or "facebook/wav2vec2-xls-r-300m"

data:
  sample_rate: 16000

train:
  batch_size: 8
  num_workers: 2
  epochs: 3
  lr: 1e-4
  weight_decay: 0.0
  grad_accum: 1
  ckpt_dir: "./checkpoints"
